### ISSUE TITLE
is here need human translator?

### ISSUE THREAD

**Issue by bestony** [MicrosoftDocs/visualstudio-docs.zh-cn#1]
I found many commits with Machine Translation and no Contributing.md At the live branch.

I want to join to translate Mac docs,Becasue I use Mac and Xamarin.

**Comment by nokura** [comment]
Heelo @bestony  Thank you for your willingness to contribute to the document. Will you refer to this section as the standard contribution guideline for docs.microsoft.com?
https://docs.microsoft.com/zh-cn/contribute/

**Comment by bestony** [comment]
Thanks!
