### ISSUE TITLE
CONTRIBUTING.md not found

### ISSUE THREAD

**Issue by jnoob** [MicrosoftDocs/visualstudio-docs.zh-cn#10]
![image](https://user-images.githubusercontent.com/16622396/35722031-ac57caa6-082f-11e8-9545-91105616c8b6.png)
![image](https://user-images.githubusercontent.com/16622396/35722051-bbd3d3e4-082f-11e8-8f4b-f7fbe58d8008.png)

**Comment by nokura** [comment]
Sorry for the confusion, but will you refer to this section as standard guideline for docs.microsoft.com?
https://docs.microsoft.com/zh-cn/contribute/
