### ISSUE TITLE
mac community版本没有这个功能吗

### ISSUE THREAD

**Issue by super918180** [MicrosoftDocs/visualstudio-docs.zh-cn#108]
mac community版本没有这个功能吗

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 970f0d59-b2b4-7082-1c2c-a468c93571ef
* Version Independent ID: a3135966-c343-5a6b-cd97-772a0c34fd93
* Content: [开发代码而无需创建项目或解决方案 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/develop-code-in-visual-studio-without-projects-or-solutions?view=vs-2017)
* Content Source: [docs/ide/develop-code-in-visual-studio-without-projects-or-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/develop-code-in-visual-studio-without-projects-or-solutions.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CeciAc** [comment]
你好，@super918180
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
