### ISSUE TITLE
一处机器翻译错误,主宾倒置

### ISSUE THREAD

**Issue by Flithor** [MicrosoftDocs/visualstudio-docs.zh-cn#109]
该文档的[Object 元素](https://docs.microsoft.com/zh-cn/visualstudio/ide/code-snippets-schema-reference?view=vs-2017#object-element)下子元素表格中"Function 元素"的说明中,机翻结果主宾倒置

文档原文
-
可选元素。 指定当文本在 Visual Studio 中获得焦点时要执行的函数。 **`Function` 元素中可能有零个或一个 `Literal` 元素**。

英文文档原文
-
Optional element. Specifies a function to execute when the literal receives focus in Visual Studio. **There may be zero or one `Function` elements in a `Literal` element**.

实际应翻译为
-
可选元素。 指定当文本在 Visual Studio 中获得焦点时要执行的函数。 **`Literal` 元素中可能有零个或一个 `Function` 元素**。

这类错误其实不在少数,很多文档中都有这种错误

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 91faad91-f76f-1c35-3ff7-b8dea92c00f1
* Version Independent ID: d974b7e1-f76a-c575-bff8-cf4d38d19771
* Content: [代码片段架构参考 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/code-snippets-schema-reference?view=vs-2017#literal-element)
* Content Source: [docs/ide/code-snippets-schema-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/code-snippets-schema-reference.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CeciAc** [comment]
你好，@Flithor
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Flithor

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/visualstudio/ide/code-snippets-schema-reference?view=vs-2017#literal-element  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Flithor
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Flithor

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面： https://docs.microsoft.com/zh-cn/visualstudio/ide/code-snippets-schema-reference?view=vs-2017

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
