### ISSUE TITLE
警告	C6001

### ISSUE THREAD

**Issue by sch984658780** [MicrosoftDocs/visualstudio-docs.zh-cn#121]
int* p = new int;
	*p= 5;
	delete p;
	cout &lt;&lt;*p&lt;&lt; endl;

显示：严重性	代码	说明	项目	文件	行	禁止显示状态
警告	C6001	使用未初始化的内存“p”。	Project1	c:\users\尚春虎\desktop\vs\project1\源.cpp	115	

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5f83734b-f26f-67c4-b004-f9fe7d2b5489
* Version Independent ID: 8c77baaa-cc80-7025-dd14-92fd55f7a0e8
* Content: [C6001 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/code-quality/c6001?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DZH-CN%26k%3Dk(C6001)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/code-quality/c6001.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/code-quality/c6001.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
Hello, @sch984658780

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
