### ISSUE TITLE
this  is nothing

### ISSUE THREAD

**Issue by dsq4500** [MicrosoftDocs/visualstudio-docs.zh-cn#125]
展开“项目和解决方案”文件夹，单击“VB 默认值”。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9a42e43e-d7e7-7f0b-9efc-86b9b19d9ce9
* Version Independent ID: 45104157-d762-7e6d-a70d-538a75ffec40
* Content: [“选项”对话框 -&gt;“项目”-&gt;“Visual Basic 默认值” - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/reference/visual-basic-defaults-projects-options-dialog-box?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/visual-basic-defaults-projects-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/reference/visual-basic-defaults-projects-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CeciAc** [comment]
你好，@dsq4500 
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@dsq4500
我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@dsq4500
再次感谢你的评论。
很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。
顺祝商祺！
Microsoft DOCS 国际团队
