### ISSUE TITLE
安装指南中的翻译错误

### ISSUE THREAD

**Issue by lonely-dream** [MicrosoftDocs/visualstudio-docs.zh-cn#126]
该文档的第三部分标题翻译有误。**`Install`** 在中文中一般被翻译为安装。原文翻译有误。

## 中文文档原文
第 3 步 - **`卸载`** Visual Studio 安装程序

## 英文文档原文
Step 3 - **`Install`** the Visual Studio installer

## 个人推荐翻译
> 第 3 步 - **`打开`** Visual Studio 安装程序

或者

> 第 3 步 - **`安装`** Visual Studio 安装程序

第二种翻译直接将 **`Install`** 替换为 **`安装`** ，但在中文语境下语义有一定偏差——不是安装Visual Studio的安装程序，而是使用Visual Studio安装程序安装Visual Studio。因此个人更为喜欢第一种翻译。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9dd4d05c-4aa3-0376-f3a1-b0ea0793f482
* Version Independent ID: 7f1ff943-61b0-60e1-9ca3-d4a84bfdb068
* Content: [安装 Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/install/install-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/install/install-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by CeciAc** [comment]
你好，@lonely-dream
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@lonely-dream

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面： https://docs.microsoft.com/zh-cn/visualstudio/install/install-visual-studio?view=vs-2019

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 

Microsoft DOCS International Team
