### ISSUE TITLE
visualstudio remote tool  download url error

### ISSUE THREAD

**Issue by HeMinzhang** [MicrosoftDocs/visualstudio-docs.zh-cn#127]
**In this doc:**
https://docs.microsoft.com/zh-cn/visualstudio/debugger/remote-debugging?view=vs-2019

![QQ截图20190511103729](https://user-images.githubusercontent.com/2683269/57564075-cfec2280-73d8-11e9-92a1-449a8da46b8f.png)

**this link:**
https://visualstudio.microsoft.com/downloads/?q=remote+tools#remote-tools-for-visual-studio-2019

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #3241](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3241) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @HeMinzhang

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/3241

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by HeMinzhang** [comment]
I think it's just a problem with the Chinese page. It only shows the error when the language is Chinese.

Other problems I just discovered:
QQ截图20190514105350

Visual Studio 2017 download link error:
https://my.visualstudio.com/Downloads?q=remote%20tools%20visual%20studio%202017
QQ截图20190514105846

Visual Studio 2015 download link error:
https://my.visualstudio.com/Downloads?q=remote%20tools%20visual%20studio%202015
QQ截图20190514105915

Visual Studio 2012 download link error(The English page is normal. The Chinese page shows Visual Studio 2013?):
https://docs.microsoft.com/zh-cn/previous-versions/visualstudio/visual-studio-2012/bt727f1t(v=vs.110)#installing-the-remote-tools

QQ截图20190514105810

**Comment by HeMinzhang** [comment]
Visual Studio 2019 download error:
![QQ截图20190514110027](https://user-images.githubusercontent.com/2683269/57667831-af6dd380-7637-11e9-876c-7e2929b49796.png)
![QQ截图20190514110118](https://user-images.githubusercontent.com/2683269/57667838-b3015a80-7637-11e9-8455-7c374e560e47.png)
