### ISSUE TITLE
有个缺点，无法传送LIST<>

### ISSUE THREAD

**Issue by alxzoom** [MicrosoftDocs/visualstudio-docs.zh-cn#128]
再尝试接口传送一个结构体的时候发现了这个问题，该结构体包含了LIST&lt;&gt;,最后只得传送Array了。不知道还有没有能传List的。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 957582d0-b341-4423-9584-eae292e83e65
* Version Independent ID: f5084455-7a3f-8c2b-a9c0-fc536194b236
* Content: [从其他 Office 解决方案调用 VSTO 外接程序中的代码 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/vsto/calling-code-in-vsto-add-ins-from-other-office-solutions?view=vs-2019#feedback)
* Content Source: [docs/vsto/calling-code-in-vsto-add-ins-from-other-office-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/vsto/calling-code-in-vsto-add-ins-from-other-office-solutions.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by CeciAc** [comment]
你好，@alxzoom
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
