### ISSUE TITLE
Print命令显示数组时不全

### ISSUE THREAD

**Issue by KevinDeng9071** [MicrosoftDocs/visualstudio-docs.zh-cn#132]
Print超过100个值的数组最后显示&lt; 更多...(显示 421 项的前 100 项。)&gt;，如何把后面的显示出来

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a313052a-9469-94f8-b58c-e70ad6edf8e2
* Version Independent ID: 9eb9f760-3ebc-3725-5ca4-aa7a9f60290e
* Content: [Debug.Print - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/reference/print-command?view=vs-2017#feedback)
* Content Source: [docs/ide/reference/print-command.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/reference/print-command.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by lichasu** [comment]
你好，@kevindeng9071

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。  

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。  

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
