### ISSUE TITLE
关于c++编译问题

### ISSUE THREAD

**Issue by Mrjerry233** [MicrosoftDocs/visualstudio-docs.zh-cn#137]
我是一个正在学习编程的学生，因为我需要多次编译cpp文件，而我不想为此建立多个解决方案，有没有办法可以直接编译（就像dev一样）希望得到回复，谢谢

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 89847656-bea8-b9a7-a50a-3d7e75e14ff6
* Version Independent ID: 9f6c1029-6d5b-1d41-10dd-65863848c2e5
* Content: [C++ 入门 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/getting-started-with-cpp-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/getting-started-with-cpp-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/getting-started-with-cpp-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @Mrjerry233
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Mrjerry233

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
