### ISSUE TITLE
The class and method is reversed

### ISSUE THREAD

**Issue by er-mao** [MicrosoftDocs/visualstudio-docs.zh-cn#16]
in this part:
[创建第一个测试方法](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md#创建第一个测试方法)

the class and method is reversed. 

I think it is just like that:

在此过程中，编写单元测试方法以验证 BankAccount 类的 Debit 方法的行为。 Debit 方法之前已在本文中显示。

**Comment by CeciAc** [comment]
你好，@er-mao  
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
你好，@er-mao  

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md#%E5%88%9B%E5%BB%BA%E7%AC%AC%E4%B8%80%E4%B8%AA%E6%B5%8B%E8%AF%95%E6%96%B9%E6%B3%95。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team
