### ISSUE TITLE
waiting for emulator 5554

### ISSUE THREAD

**Issue by merria28** [MicrosoftDocs/visualstudio-docs.zh-cn#160]
I run the project: hello-jni from https://code.msdn.microsoft.com/hello-jni-Android-790ab73d,
but a tip occurs: waiting for emutor 5554.

Does it mean i uninstalled the vs-emulator?
Or it mean any errors?

How should i do

**Comment by srvbpigh** [comment]
Hello, @merria28
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @merria28

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
