### ISSUE TITLE
Does VSTO project supports visit network and file system?

### ISSUE THREAD

**Issue by GvcZhang** [MicrosoftDocs/visualstudio-docs.zh-cn#164]
If a create a Excel plugin demo by use VSTO, can the demo support visit network and filesystem?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ccf9a3a9-baf0-3ad5-350f-f4a4eeebea11
* Version Independent ID: f73808db-0922-8266-7a85-90dce0229d65
* Content: [Office 解决方案开发概述 (VSTO) - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/vsto/office-solutions-development-overview-vsto?view=vs-2019)
* Content Source: [docs/vsto/office-solutions-development-overview-vsto.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/vsto/office-solutions-development-overview-vsto.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by srvbpigh** [comment]
Hello, @GvcZhang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #4224](https://github.com/MicrosoftDocs/visualstudio-docs/issues/4224) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @GvcZhang

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4224

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by John-Hart** [comment]
@GvcZhang, could you please provide more information regarding your question?  I'm not clear on what you mean by "can the demo support visit network and filesystem"?

**Comment by GvcZhang** [comment]
For example, I use VSTO create a project for Excel, I want the project can visit network and filesystem, because I want to send some data to my server
