### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by xujiayi1256** [MicrosoftDocs/visualstudio-docs.zh-cn#167]
文章底部“深入了解”第二行，GitHub拼错了。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: cc75bfc2-1716-d42e-9d49-5170e2f006b1
* Version Independent ID: 67d64989-787f-cb21-9c38-6960bde11256
* Content: [学习 Visual Studio 中的 Flask 教程的第 4 步，Web 项目模板](https://docs.microsoft.com/zh-cn/visualstudio/python/learn-flask-visual-studio-step-04-full-flask-project-template?view=vs-2019#feedback)
* Content Source: [docs/python/learn-flask-visual-studio-step-04-full-flask-project-template.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/python/learn-flask-visual-studio-step-04-full-flask-project-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by srvbpigh** [comment]
Hello, @xujiayi1256
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@xujiayi1256  

感谢你的反馈。  

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/visualstudio/python/learn-flask-visual-studio-step-04-full-flask-project-template?view=vs-2019#feedback。   

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福，  
Microsoft DOCS International Team
