### ISSUE TITLE
安装程序启动遇到的问题

### ISSUE THREAD

**Issue by suzic** [MicrosoftDocs/visualstudio-docs.zh-cn#168]
Visual Studio 2019 for Mac安装包启动后，出现一个提示对话框，完整信息如下：

（黄色感叹号）出现错误...
无法访问“/etc/paths.d/.mypath.swp" - 请进行修复并
稍后重试。
（按钮：退出）

我不太明白其中的原因，修复的话，又该如何进行？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c3989ef3-79d0-03b7-6a17-749ee96b9550
* Version Independent ID: 3a66757e-649d-6415-ff5e-00d628eb17f6
* Content: [安装 Visual Studio 2019 for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/zh-cn/visualstudio/mac/installation?view=vsmac-2019#feedback)
* Content Source: [mac/installation.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/mac/installation.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by srvbpigh** [comment]
Hello, @suzic
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@suzic

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
