### ISSUE TITLE
最新的VS09（16.4.2）版本X64工程没有链接选项，但是win32有。

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/visualstudio-docs.zh-cn#169]
如题。

难道是我安装的问题。

这里不能发表图片，能有图片最好了。

X64的工程属性页比win32的工程属性页少了好多内容。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2e5b432e-98af-2784-12f3-5da298a7a6a3
* Version Independent ID: 0d0b207d-4ea3-3716-3894-b898b279e667
* Content: [项目和解决方案简介 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/get-started/tutorial-projects-solutions?view=vs-2019)
* Content Source: [docs/get-started/tutorial-projects-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/get-started/tutorial-projects-solutions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by srvbpigh** [comment]
Hello, @kouzhudong
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by kouzhudong** [comment]
![image](https://user-images.githubusercontent.com/18212165/71143021-100b6180-2254-11ea-9991-c5ea2ec72a4d.png)

![image](https://user-images.githubusercontent.com/18212165/71143049-22859b00-2254-11ea-9dcd-d365922fd106.png)

看到差别没？

VS创建的示例工程。

**Comment by CeciAc** [comment]
你好，@kouzhudong 

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
