### ISSUE TITLE
删除下载的组建

### ISSUE THREAD

**Issue by mirocosphp** [MicrosoftDocs/visualstudio-docs.zh-cn#170]
如何删除终止Visual Studio 2019 For mac 安装时已经下载的组件。

**Comment by srvbpigh** [comment]
Hello, @mirocosphp
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@mirocosphp 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4551。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @microsphp

@WilliamAntonRohm commented:
It looks like you’re having an issue with installation. If your Visual Studio installation fails, see Troubleshooting Visual Studio installation and upgrade issues (https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​

We also offer a Live Chat (https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​

Here are a few more support options:​

    Report product issues to us via the Report a Problem(https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​
    Suggest a feature, track product issues, and find answers in the Visual Studio Developer Community. (https://developercommunity.visualstudio.com/)
    Use your GitHub account to talk to us and other Visual Studio developers in the Visual Studio conversation in the Gitter community. (https://gitter.im/Microsoft/VisualStudio) 

#please-translate

**Comment by srvbpigh** [comment]
从上述备注开始翻译 

你好，@microsphp
@WilliamAntonRohm 批注：
你似乎在安装方面遇到问题。如果 Visual Studio 安装失败，请参阅“排查 Visual Studio 安装和升级问题” (https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) 获取分步指南。

对于与安装相关的问题，我们还会提供实时聊天(https://visualstudio.microsoft.com/vs/support/#talktous)（仅限英语）支持选项。

下面是其他一些支持选项：

可通过“报告问题”(https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) 问题向我们报告产品问题，Visual Studio 安装程序和 Visual Studio IDE 中都有此工具。
可在 Visual Studio 开发者社区 (https://developercommunity.visualstudio.com/) 建议功能、跟踪产品问题和查找答案。
可使用 GitHub 帐户在 Gitter 社区 (https://gitter.im/Microsoft/VisualStudio) 中通过 Visual Studio 对话与我们和其他 Visual Studio 开发人员交谈。

**Comment by conceptdev** [comment]
[卸载Visual Studio for Mac](https://docs.microsoft.com/zh-cn/visualstudio/mac/uninstall?view=vsmac-2019)
