### ISSUE TITLE
病句。 “Uri 类以安全安全的方式提供这些服务”。

### ISSUE THREAD

**Issue by icortana** [MicrosoftDocs/visualstudio-docs.zh-cn#172]
规则描述中， “Uri 类以安全安全的方式提供这些服务“。
应该修改为 “Uri 类以安全的方式提供这些服务“

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 366958d0-72cf-f782-5322-539bab3c862b
* Version Independent ID: 4caba8dd-9ce3-5055-9450-5544d0a353a4
* Content: [CA2234：传递 System.Uri 对象，而不传递字符串 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/code-quality/ca2234?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca2234.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/code-quality/ca2234.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by srvbpigh** [comment]
Hello, @icortana
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Case #15: Stop MT GH ISSUE related with linguistic issue (01/09/2020) 

 

 

@
@icortana  您好： 

感謝您的參與。 

目前不接受參與機器翻譯內容的翻譯問題。 

我們很重視您對人工翻譯內容的意見反應與建議，並使用這些意見來訓練機器翻譯引擎，因此，您的貢獻內容會隨著時間改善人工與機器翻譯的品質。 

您可以根據各個內容檔案標頭的 ms.translationtype 中繼資料值 “HT”，分辨出人工翻譯的主題，其他則是機器翻譯的主題 (值為 “MT” 代表機器翻譯)。 

非常感謝您的支援。 

Microsoft DOCS 全球體驗小組
