### ISSUE TITLE
how much RAM do I need？

### ISSUE THREAD

**Issue by 3056521761** [MicrosoftDocs/visualstudio-docs.zh-cn#175]
In VMWare Workstation（With unlocker）and VirtualBox，we can create virtual machines with Mac OS，so you should tell us how much RAM I need in this doc

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c3989ef3-79d0-03b7-6a17-749ee96b9550
* Version Independent ID: 3a66757e-649d-6415-ff5e-00d628eb17f6
* Content: [安装 Visual Studio 2019 for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/zh-cn/visualstudio/mac/installation?view=vsmac-2019)
* Content Source: [mac/installation.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/mac/installation.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by srvbpigh** [comment]
Hello, @3056521761
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @3056521761,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
