### ISSUE TITLE
doc is wrong

### ISSUE THREAD

**Issue by nicol-go** [MicrosoftDocs/visualstudio-docs.zh-cn#178]
The part of "Run diagnostic sessions on installed or running apps" is out-dated. This way cannot work well in VS2019. Could you update the document?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e998101e-f5d8-517a-7f74-356b973a2b07
* Version Independent ID: 36f07905-43eb-019a-a0f6-a732b9d10da6
* Content: [运行带或不带调试器的分析工具 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/profiling/running-profiling-tools-with-or-without-the-debugger?view=vs-2019)
* Content Source: [docs/profiling/running-profiling-tools-with-or-without-the-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/profiling/running-profiling-tools-with-or-without-the-debugger.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by srvbpigh** [comment]
Hello, @nicol-go
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #4924](https://github.com/MicrosoftDocs/visualstudio-docs/issues/4924) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@nicol-go 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4924。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
