### ISSUE TITLE
如何在生成后事件命令行中启动一个服务程序？

### ISSUE THREAD

**Issue by wukongabc123** [MicrosoftDocs/visualstudio-docs.zh-cn#185]
如题，如果这个服务不终止，则生成过程会一直等待。进度条会卡住，直到关闭该程序。
我想实现的效果是，当生成完将文件拷贝到目的目录之后，重启服务。但是，现在服务已启动，就把生成过程给卡住了。生成的进度条显示在最后几步一直不懂，直到关闭这个用命令行启动的程序。
how to start a service program after the After-Generated event using command line.
I tried "start xxxService.exe","call StartxxxService.bat","xxxService.exe" and so on,while all of them would stuck the  generating progress. 
The purpose I want to accomplish is that after coping the generated files, restart the service.
however i was stuck here.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 319cf42a-5391-8a60-c005-cfbb92faf1c8
* Version Independent ID: ef79e00a-e2c9-12ec-6da9-2984c381e7d1
* Content: [预生成事件/生成后事件命令行对话框 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/reference/pre-build-event-post-build-event-command-line-dialog-box?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/pre-build-event-post-build-event-command-line-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/reference/pre-build-event-post-build-event-command-line-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @wukongabc123
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #5114](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5114) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@wukongabc123 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/visualstudio-docs/issues/5114。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
