### ISSUE TITLE
微软办公室主交互程序集的组件 ID   EXCEL 2019 

### ISSUE THREAD

**Issue by jinzi960423** [MicrosoftDocs/visualstudio-docs.zh-cn#187]
微软办公室主交互程序集的组件 ID   

EXCEL 2019   组件 ID   是多少？在哪里可以查的到！

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3df9904c-bc2c-49e6-b661-5598354dbc40
* Version Independent ID: 6dca41d0-9c34-f5cc-a2b0-6c6e9df76063
* Content: [使用 Windows 安装程序部署用于办公室解决方案的可视化工作室工具 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer?view=vs-2019)
* Content Source: [docs/vsto/deploying-a-vsto-solution-by-using-windows-installer.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/vsto/deploying-a-vsto-solution-by-using-windows-installer.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by srvbpigh** [comment]
Hello, @jinzi960423
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #5192](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5192) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@jinzi960423 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/visualstudio-docs/issues/5192。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
