### ISSUE TITLE
创建多项目模板，用.vsix生成出来多一层目录

### ISSUE THREAD

**Issue by liuwen85138342** [MicrosoftDocs/visualstudio-docs.zh-cn#189]
创建多项目模板，用.vsix生成出来多一层目录

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 35146821-db5a-b376-b264-26fd5d0d56e1
* Version Independent ID: cff5ba90-e570-3a44-ad6f-48da0ab17b30
* Content: [对项目模板和项模板加载进行故障排除 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/how-to-troubleshoot-templates?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-troubleshoot-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/how-to-troubleshoot-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @liuwen85138342
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@liuwen85138342

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@liuwen85138342

再次感谢你的评论。 

很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。 

顺祝商祺！ 

Microsoft DOCS 国际团队
