### ISSUE TITLE
Too many referred link.

### ISSUE THREAD

**Issue by dhlolo-envision** [MicrosoftDocs/visualstudio-docs.zh-cn#19]
Too many referred link.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ccf9a3a9-baf0-3ad5-350f-f4a4eeebea11
* Version Independent ID: f73808db-0922-8266-7a85-90dce0229d65
* Content: [Office 解决方案开发概述 (VSTO)](https://docs.microsoft.com/zh-cn/visualstudio/vsto/office-solutions-development-overview-vsto)
* Content Source: [docs/vsto/office-solutions-development-overview-vsto.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/vsto/office-solutions-development-overview-vsto.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by LisandroSu** [comment]
Hello, @dhlolo-envision , 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @dhlolo-envision , 
  
Thank you for your feedback. We need more information to be able to deal with this issue. Can you please provide more detailed instructions and specific lines that need revision/fixing? 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @dhlolo-envision ,
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
