### ISSUE TITLE
MSB6006: "clcache_main.exe" Probabilistic appearance

### ISSUE THREAD

**Issue by yebanqingxing123** [MicrosoftDocs/visualstudio-docs.zh-cn#190]
[在此处输入反馈]

D:\VS2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(358,5): error MSB6006: "clcache_main.exe" exited with code -1.
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [报告问题：状态和常见问题解答 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/report-a-problem?view=vs-2019)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/report-a-problem.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by srvbpigh** [comment]
Hello, @yebanqingxing123
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @yebanqingxing123 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by yebanqingxing123** [comment]
D:\VS2017\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(358,5): error MSB6006: "clcache_main.exe" exited with code -1. [D:\work_code\libai_fmk_tensorflow_parser\libai_fmk_tensorflow_parser.vcxproj]

**Comment by CeciAc** [comment]
Hello, @yebanqingxing123 

Thanks once again for your comment. 

Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future. 

Kind regards, 

Microsoft DOCS International Team
