### ISSUE TITLE
您好，我想问一下为什么我的VS2019只有debug模式没有release模式呢？

### ISSUE THREAD

**Issue by wang-zm18** [MicrosoftDocs/visualstudio-docs.zh-cn#195]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4938a042-e5db-4f9c-2288-930b904e888c
* Version Independent ID: 6db1e386-22e4-4940-cc2c-bdeaa5883299
* Content: [如何：更改生成输出目录 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/how-to-change-the-build-output-directory?view=vs-2019)
* Content Source: [docs/ide/how-to-change-the-build-output-directory.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/how-to-change-the-build-output-directory.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by srvbpigh** [comment]
Hello, @wang-zm18
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@wang-zm18

非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。 

如果你有任何与文档相关的反馈，请通过此渠道进行记录。 

我们非常感谢你对我们的文章的贡献。 

Microsoft DOCS 国际团队
