### ISSUE TITLE
文档标题有误

### ISSUE THREAD

**Issue by jiangtiandao** [MicrosoftDocs/visualstudio-docs.zh-cn#24]
应该是 仅使用键盘进行操作

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d6452222-881f-0b4e-447f-7ad35230ab31
* Version Independent ID: 2037a1d4-a9e0-e569-c73f-200df1278ee0
* Content: [如何：以独占方式使用键盘](https://docs.microsoft.com/zh-cn/visualstudio/ide/reference/how-to-use-the-keyboard-exclusively)
* Content Source: [docs/ide/reference/how-to-use-the-keyboard-exclusively.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/reference/how-to-use-the-keyboard-exclusively.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by LisandroSu** [comment]
您好，@jiangtiandao

感谢您的反馈意见。 我们需要更多信息才能处理这个问题。 您能否提供更详细的说明和需要修改/修复的具体行？
 
亲切的问候，
Microsoft DOCS国际团队

**Comment by jiangsheng** [comment]
已经在#25 里修正

**Comment by larry801** [comment]
Close #24

**Comment by CeciAc** [comment]
你好，@jiangtiandao

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/visualstudio/ide/reference/how-to-use-the-keyboard-exclusively。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team

**Comment by jiangsheng** [comment]
上面的回复里那个链接是死链接啊

**Comment by CeciAc** [comment]
修复
