### ISSUE TITLE
我在开发一些js uwp 游戏,有些问题请帮助

### ISSUE THREAD

**Issue by 958877748** [MicrosoftDocs/visualstudio-docs.zh-cn#31]
如何在所有设备上保证 window.devicePixelRatio = 1,
不然他就会模糊,因为他是一个像素风格的游戏,我需要把像素对齐

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b34e867a-5189-f8b1-6ea0-4adc0201a8d3
* Version Independent ID: 7bf02488-2f88-75da-89b7-671c353a4514
* Content: [解决 DPI 问题 2](https://docs.microsoft.com/zh-cn/visualstudio/extensibility/addressing-dpi-issues2)
* Content Source: [docs/extensibility/addressing-dpi-issues2.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/extensibility/addressing-dpi-issues2.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by LisandroSu** [comment]
你好，@958877748

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by 958877748** [comment]
我关心的问题如何解决呢?可我还没找到答案

**Comment by LisandroSu** [comment]
你好，@958877748

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。

非常感谢你对我们的文章作出的贡献。

深深的祝福，
Microsoft DOCS International Team
