### ISSUE TITLE
无法打开源文件"stdafx.h"

### ISSUE THREAD

**Issue by IamDead** [MicrosoftDocs/visualstudio-docs.zh-cn#32]
按照文中所述步骤创建“C++ Windows 控制台应用程序”后，在编辑代码过程中提示“无法打开源文件"stdafx.h"”，并且默认使用的是“#include "pch.h"”，是文中内容有误还是我需要更改设置？
——VS2017社区版15.8.1

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 89847656-bea8-b9a7-a50a-3d7e75e14ff6
* Version Independent ID: 9f6c1029-6d5b-1d41-10dd-65863848c2e5
* Content: [Visual Studio 中的 C++ 入门](https://docs.microsoft.com/zh-cn/visualstudio/ide/getting-started-with-cpp-in-visual-studio)
* Content Source: [docs/ide/getting-started-with-cpp-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/getting-started-with-cpp-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @corob-msft
* Microsoft Alias: **tglee**

**Comment by gosali** [comment]
你好，@IamDead  

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/visualstudio-docs/issues/1408。  

非常感谢你对我们的文章作出的贡献。   
深深的祝福，  
Microsoft DOCS International Team
