### ISSUE TITLE
希望稍加配置就能在vs2017中打开VS2015和VS2013建模图形

### ISSUE THREAD

**Issue by zszyj72** [MicrosoftDocs/visualstudio-docs.zh-cn#36]
Microsoft Visual Studio（以下简称Vs）2013和Vs2015中的建模功能还是很不错的，能满足应用开发构建时的建模需求。但在Vs2017中没有该项功能，导致Vs2017不能打开Vs2015、Vs2013工程项目中使用Modeling建模的UML图形（包括UML类图、UML序列图、UML用例图、UML活动图、UML组件图），如下图所示。

通过查找%userprofile%\Documents\Visual Studio 2013\Settings\CurrentSettings.vssettings和%userprofile%\Documents\Visual Studio 2015\Settings\CurrentSettings.vssettings两个文件中关于类图的定义都差不多，以下摘录了Vs2013 CurrentSettings.vssettings的设置信息：
&lt;Scope Name="UML Class Diagram" ID="{FE170F05-DE3A-4067-A3ED-08AE56B31DB3}"/&gt;&lt;Scope Name="UML Component Diagram" ID="{13C19B18-BD05-42F3-9D3A-2A55E6E9169F}"/&gt;
&lt;Scope Name="Class Diagram" ID="{59B0B277-7DDF-4E36-A3ED-02DAC5B9E2FA}"/&gt;&lt;Scope Name="UML Activity Diagram" ID="{950C3878-B510-4BC5-9051-42798A870364}"/&gt;&lt;Scope Name="UML Use Case Diagram" ID="{FCFECC7C-3151-4B48-A85A-909F50500A70}"/&gt;
&lt;Scope Name="Sequence Diagram" ID="{5028BC9F-844B-4C51-A624-0005945D14AE}"/&gt;
因此推测，如果在安装有vs2013的计算机系统中是否稍加配置就能在vs2017中使用vs2013和vs2015的建模功能。在vs2017 保留UML designers还是十分有用及必要的。
谢谢。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d648cd73-34e8-1a47-35cc-3c5a1ff9f8f5
* Version Independent ID: a02d528a-85f7-00f6-cf00-3416713ed4d9
* Content: [如何报告 Visual Studio 2017 的问题 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio-2017.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/how-to-report-a-problem-with-visual-studio-2017.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by LisandroSu** [comment]
你好，@zszyj72

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
