### ISSUE TITLE
666

### ISSUE THREAD

**Issue by licoba** [MicrosoftDocs/visualstudio-docs.zh-cn#39]
還可以這樣的！

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 14465304-3ced-6b36-5054-a85ac11e667e
* Version Independent ID: 9d2d9ca3-8d71-b81c-dbbb-bf4b269db034
* Content: [在 Visual Studio 中使用 Xamarin 生成具有本机 UI 的应用 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio?view=vs-2017)
* Content Source: [docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by LisandroSu** [comment]
你好，@licoba

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by LisandroSu** [comment]
你好，@licoba

我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by LisandroSu** [comment]
你好，@licoba

再次感谢你的评论。
很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。

顺祝商祺！
Microsoft DOCS 国际团队
