### ISSUE TITLE
cannot run project

### ISSUE THREAD

**Issue by qssq** [MicrosoftDocs/visualstudio-docs.zh-cn#40]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB6006	“clang.exe”已退出，代码为 2。	hello-jni.NativeActivity	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Clang.targets	212	
错误		Unable to open file E:\cross-c\hello-jni Android Application Sample\C++\ARM\Debug\libhello-jni.so.recipe because 2	hello-jni.Packaging	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\MDD\Android\V150\Android.Common.targets	261	

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: caf3cc14-c914-da3a-b3ae-7e2d80712166
* Version Independent ID: 070a2258-3275-f62c-bb92-33067da26698
* Content: [跨平台移动开发示例 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/cross-platform/cross-platform-mobile-development-examples?view=vs-2017)
* Content Source: [docs/cross-platform/cross-platform-mobile-development-examples.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/cross-platform/cross-platform-mobile-development-examples.md)
* Product: **visual-studio-dev15**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by qssq** [comment]
Failed to connect to and resume the Android Java Virtual Machine

**Comment by qssq** [comment]
phone waiting for Debugger

**Comment by qssq** [comment]
编译通过了，但是无法调试，请问JniEnv有红线怎么办 ，我添加关联没啥用
我想用visual studio开发c++ jni项目

**Comment by CeciAc** [comment]
你好，@qssq 

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
