### ISSUE TITLE
yas

### ISSUE THREAD

**Issue by yuwejia** [MicrosoftDocs/visualstudio-docs.zh-cn#76]
good

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: db7f9ca8-40ce-6b6d-15df-bbb3b6829430
* Version Independent ID: 3dd10fed-b3d3-269c-623e-00031a81ed83
* Content: [快速入门：使用 Visual Studio 创建 Python Web 应用 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/quickstart-python?view=vs-2017)
* Content Source: [docs/ide/quickstart-python.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/quickstart-python.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by CeciAc** [comment]
Hello, @yuwejia 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continually improve your experience.

Kind regards,
Microsoft DOCS International Team
