### ISSUE TITLE
怎么使用断点调试程序呢？(how to debug that？)

### ISSUE THREAD

**Issue by lylxiaole** [MicrosoftDocs/visualstudio-docs.zh-cn#95]
怎么使用断点调试程序呢？(how to debug that？)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 59adf9c7-5894-84ba-32ee-df842aa4658d
* Version Independent ID: 50683e7c-4b31-1773-f20e-00732a0ffbcc
* Content: [快速入门：创建第一个 Vue.js 应用 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/javascript/quickstart-vuejs-with-nodejs?view=vs-2017#next-steps)
* Content Source: [docs/javascript/quickstart-vuejs-with-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/javascript/quickstart-vuejs-with-nodejs.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by CeciAc** [comment]
你好，@lylxiaole

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
